module.exports = {
  path: '/data/v1/object/user',
  method: 'POST',
  contentType: 'application/x-ndjson',
  data: () => {
    return `{ "client_user_id": "0", "first_name": "Stampin\'", "last_name": "Up!", "email": "donotship@donotship.com", "home_phone": "8007826787", "mobile_phone": "", "address": "Do Not Ship", "address2": "", "city": "Do Not Ship", "postal_code": "84105", "country": "US", "signup_date": "2004-04-19", "birth_date": "1988-01-01", "company_name": "Up!, Stampin\'", "rank": {   "id": "1",   "description": "Bronze" }, "type": {   "id": "2",   "description": "Distributor" }, "status": {   "id": "1",   "description": "Active" }, "upline": {   "client_sponsor_id": "0" } }
    { "client_user_id": "1", "first_name": "Margaret", "last_name": "Goodfellow", "email": "stampeders@ymail.com", "home_phone": "8018763345", "mobile_phone": "9093762237", "address": "8149 S. 2475 E.", "address2": "", "city": "South Weber", "postal_code": "84405", "country": "US", "signup_date": "1988-09-30", "birth_date": "1990-09-07", "company_name": "Stampeders ", "rank": {   "id": "5",   "description": "Gold" }, "type": {   "id": "2",   "description": "Distributor" }, "status": {   "id": "1",   "description": "Active" }, "upline": {   "client_sponsor_id": "0" } }
    { "client_user_id": "2", "first_name": "Janet", "last_name": "Baker", "email": "JANET@STAMPPEDDLERS.COM", "home_phone": "4358659551", "mobile_phone": "", "address": "123 South Main", "address2": "", "city": "New Harmony", "postal_code": "84757", "country": "US", "signup_date": "1988-09-30", "birth_date": "1952-03-31", "company_name": "Party Peddlers, Inc", "rank": {   "id": "7",   "description": "Platinum" }, "type": {   "id": "2",   "description": "Distributor" }, "status": {   "id": "1",   "description": "Active" }, "upline": {   "client_sponsor_id": "0" } }
    { "client_user_id": "5", "first_name": "Jill", "last_name": "Olsen", "email": "SUDEMONSTRATOR@gmail.com", "home_phone": "4356738180", "mobile_phone": "4356694643", "address": "2183 S Harmony Place", "address2": "", "city": "Saint George", "postal_code": "84790", "country": "US", "signup_date": "1988-09-30", "birth_date": "1959-11-26", "company_name": "Creative Stampers, Inc", "rank": {   "id": "8",   "description": "Platunum Elite" }, "type": {   "id": "2",   "description": "Distributor" }, "status": {   "id": "1",   "description": "Active" }, "upline": {   "client_sponsor_id": "2" } }
    { "client_user_id": "20", "first_name": "Stampin\'", "last_name": "Up!", "email": "dsview@stampiup.com", "home_phone": "8007826787", "mobile_phone": "1234567890", "address": "12907 S. 3600 W.", "address2": "", "city": "Riverton", "postal_code": "84065", "country": "US", "signup_date": "2004-10-25", "birth_date": "1960-01-09", "company_name": "Up!, Stampin\'", "rank": {   "id": "1",   "description": "Bronze" }, "type": {   "id": "2",   "description": "Distributor" }, "status": {   "id": "1",   "description": "Active" }, "upline": {   "client_sponsor_id": "0" } }`
  }
}